### ISSUE TITLE
Could not pass event PrepareAnvilEvent to AdditionsAPI v1.2.9

### ISSUE THREAD

**Issue by andris155** [chrismin13/AdditionsAPI#3]
```
[17:18:36] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to AdditionsAPI v1.2.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1373]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1052) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.e(ContainerAnvil.java:296) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.a(ContainerAnvil.java:109) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.ContainerAnvil$1.update(ContainerAnvil.java:20) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:146) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.Slot.set(SourceFile:79) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.Container.a(Container.java:543) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.shiftClick(ContainerAnvil.java:333) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.Container.a(Container.java:251) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1989) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1373]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1373]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.chrismin13.additionsapi.items.CustomItemStack.updateLore(CustomItemStack.java:366) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.additionsapi.items.CustomItemStack.updateLore(CustomItemStack.java:335) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.additionsapi.listeners.vanilla.Anvil.onItemRename(Anvil.java:77) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor173.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1373]
	... 25 more
[17:18:36] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to AdditionsAPI v1.2.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1373]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1052) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.e(ContainerAnvil.java:296) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.a(ContainerAnvil.java:109) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.ContainerAnvil$1.update(ContainerAnvil.java:20) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.Slot.f(SourceFile:84) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.Slot.set(SourceFile:80) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.Container.a(Container.java:543) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.shiftClick(ContainerAnvil.java:333) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.Container.a(Container.java:251) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1989) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1373]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1373]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.chrismin13.additionsapi.items.CustomItemStack.updateLore(CustomItemStack.java:366) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.additionsapi.items.CustomItemStack.updateLore(CustomItemStack.java:335) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.additionsapi.listeners.vanilla.Anvil.onItemRename(Anvil.java:77) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor173.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1373]
	... 25 more
```

**Comment by chrismin13** [comment]
Fixed in the upcoming 1.3.0 release.
