### ISSUE TITLE
Java 10 and Java 11 error

### ISSUE THREAD

**Issue by andris155** [chrismin13/AdditionsAPI#30]
```
[16:16:10] [Server thread/WARN]: [AdditionsAPI] Task #11 for AdditionsAPI v1.3.2 generated an exception
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at us.fihgu.toolbox.resourcepack.ResourcePackManager.buildResourcePack(ResourcePackManager.java:149) ~[?:?]
	at com.chrismin13.additionsapi.AdditionsAPI.setupHTTPServer(AdditionsAPI.java:189) ~[?:?]
	at com.chrismin13.additionsapi.AdditionsAPI.load(AdditionsAPI.java:214) ~[?:?]
	at com.chrismin13.additionsapi.AdditionsAPI.lambda$onEnable$0(AdditionsAPI.java:176) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-413]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-413]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-413]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-413]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-413]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-413]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-413]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-413]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 11 more
```

**Comment by chrismin13** [comment]
Thank you very much for the pull request! I have merged then and will be testing them soon.
