### ISSUE TITLE
AdditionsAPI not compatible HideAndSeek plugin

### ISSUE THREAD

**Issue by andris155** [chrismin13/AdditionsAPI#38]
```
[11:52:50] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to AdditionsAPI v1.3.3
java.lang.NullPointerException: null
    at com.chrismin13.additionsapi.listeners.vanilla.PlayerDeath.onPlayerDeath(PlayerDeath.java:21) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at me.wazup.hideandseek.HASListener$2.run(HASListener.java:638) ~[?:?]
    at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-"4b854b5b"]
    at java.lang.Thread.run(Unknown Source) [?:?]
```
https://www.spigotmc.org/resources/hideandseek.9777/
<img width="656" alt="Annotation 2019-08-22 112853" src="https://user-images.githubusercontent.com/8324198/63503588-0bb28000-c4d0-11e9-8788-420e07a35325.png">

**Comment by BigBadE** [comment]
Fixed by adding
`if(msg == null) return;`
to PlayerDeath.java

I don't think that will break anything.
