### ISSUE TITLE
Could not pass event PlayerCustomItemDamageEvent to AdditionsAPI v1.2.9

### ISSUE THREAD

**Issue by andris155** [chrismin13/AdditionsAPI#4]
```
[20:23:31] [Server thread/ERROR]: Could not pass event PlayerCustomItemDamageEvent to AdditionsAPI v1.2.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1349]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1349]
	at com.chrismin13.additionsapi.items.CustomItemStack.reduceDurability(CustomItemStack.java:322) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.abilities.SickleAbilities.onUse(SickleAbilities.java:35) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.listeners.BlockBreakListener.onCustomItemBlockBreak(BlockBreakListener.java:32) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor246.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1349]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1349]
	at com.chrismin13.additionsapi.listeners.vanilla.BlockBreak.onBlockBreak(BlockBreak.java:23) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor175.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1349]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:192) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:914) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1349]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1349]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.chrismin13.additionsapi.items.CustomItemStack.getFakeDurability(CustomItemStack.java:250) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.additionsapi.listeners.custom.PlayerCustomItemDamage.onPlayerCustomItemDamage(PlayerCustomItemDamage.java:45) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor184.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1349]
	... 34 more
```

**Comment by chrismin13** [comment]
This error should be impossible, could you please post how it happened and any way to reproduce it?

**Comment by andris155** [comment]
```
[14:39:52] [Server thread/ERROR]: Could not pass event PlayerCustomItemDamageEvent to AdditionsAPI v1.3.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1533]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1533]
	at com.chrismin13.additionsapi.items.CustomItemStack.reduceDurability(CustomItemStack.java:322) ~[?:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller$1.run(TreeFeller.java:308) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at com.chrismin13.additionsapi.items.CustomItemStack.getFakeDurability(CustomItemStack.java:250) ~[?:?]
	at com.chrismin13.additionsapi.listeners.custom.PlayerCustomItemDamage.onPlayerCustomItemDamage(PlayerCustomItemDamage.java:45) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor196.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1533]
	... 13 more
```

**Comment by andris155** [comment]
I don't know. But flood this error in console sometimes.

**Comment by chrismin13** [comment]
Update both Vanilla Additions and the Additions API to the latest version.

**Comment by andris155** [comment]
This is the latest plugin version error.

**Comment by chrismin13** [comment]
Maybe it's paper Spigot? Honestly, I'm clueless. Find a way to replicate it, so I can try it out and see why it occurs.

**Comment by andris155** [comment]
Yes.
```
08.08 16:58:52 [Server] INFO This server is running Paper version git-Paper-1533 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
08.08 16:58:52 [Server] INFO Previous version: git-Paper-1532 (MC: 1.12.2)
08.08 16:58:52 [Server] INFO Checking version, please wait...
08.08 16:58:53 [Server] INFO You are running the latest version
```
