### ISSUE TITLE
Crashes because cannot find FileUtils

### ISSUE THREAD

**Issue by gabsoftware** [chrismin13/AdditionsAPI#41]
When I run my Spigot 1.14.4, I got the following error:
```
[15:21:04] [Server thread/WARN]: [AdditionsAPI] Task #6 for AdditionsAPI v1.3.2 generated an exception
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at us.fihgu.toolbox.file.FileUtils.deleteFolder(FileUtils.java:60) ~[?:?]
        at us.fihgu.toolbox.resourcepack.ResourcePackManager.buildResourcePack(ResourcePackManager.java:113) ~[?:?]
        at com.chrismin13.additionsapi.AdditionsAPI.setupHTTPServer(AdditionsAPI.java:189) ~[?:?]
        at com.chrismin13.additionsapi.AdditionsAPI.load(AdditionsAPI.java:214) ~[?:?]
        at com.chrismin13.additionsapi.AdditionsAPI.lambda$onEnable$0(AdditionsAPI.java:176) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]oo
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 12 more
```

So I downloaded a commons-io-2.6.jar and tried a whole lot of things like adding "-classpath /path/to/commons-io-2.6.jar -Djava.library.path=/path/to/" in the Spigot command line or in the Spigot BuildTools command line but that changes nothing. From my little understanding of how Java works, this library should be linked at compile time when you compile the AdditionsAPI plugin. Correct?

**Comment by chrismin13** [comment]
Correct! What I think is going on here is that one of your other plugins already has commons-io and it's an older version. It might also be that 1.14 no longer includes the commons-io jar. Could you try it with the same Spigot jar but without any plugins added?

**Comment by gabsoftware** [comment]
Yep, still crashes with only Additions API and Vanilla Additions plugins.

`minecraft@vps-197118:~$ java -jar spigot-1.14.4.jar
Loading libraries, please wait...
[13:39:32] [Server thread/INFO]: Starting minecraft server version 1.14.4
[13:39:32] [Server thread/INFO]: Loading properties
[13:39:32] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-94af569-6ddeb98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[13:39:32] [Server thread/INFO]: Debug logging is disabled
[13:39:32] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:39:32] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:39:32] [Server thread/INFO]: Default game type: SURVIVAL
[13:39:32] [Server thread/INFO]: Generating keypair
[13:39:33] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:39:33] [Server thread/INFO]: Using epoll channel type
[13:39:33] [Server thread/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 94:8d:78:52:7e:86:36:29
[13:39:39] [Server thread/INFO]: [AdditionsAPI] Loading AdditionsAPI v1.3.2
[13:39:39] [Server thread/INFO]: [VanillaAdditions] Loading VanillaAdditions v1.3.3
[13:39:39] [Server thread/INFO]: Preparing level "GabLand2"
[13:39:39] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[13:39:48] [Server thread/INFO]: Loaded 6 recipes
[13:39:49] [Server thread/INFO]: -------- World Settings For [GabLand2] --------
[13:39:49] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Carrot Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Potato Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Vine Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Kelp Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:39:49] [Server thread/INFO]: Mob Spawn Range: 6
[13:39:49] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[13:39:49] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:39:49] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:39:49] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[13:39:49] [Server thread/INFO]: Max TNT Explosions: 100
[13:39:49] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:39:49] [Server thread/INFO]: View Distance: 10
[13:39:49] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:39:49] [Server thread/INFO]: Item Despawn Rate: 6000
[13:39:49] [Server thread/INFO]: Item Merge Radius: 2.5
[13:39:49] [Server thread/INFO]: Arrow Despawn Rate: 1200
[13:39:49] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:39:49] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:39:49] [Server thread/INFO]: -------- World Settings For [GabLand2_nether] --------
[13:39:49] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Carrot Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Potato Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Vine Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Kelp Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:39:49] [Server thread/INFO]: Mob Spawn Range: 6
[13:39:49] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[13:39:49] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:39:49] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:39:49] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[13:39:49] [Server thread/INFO]: Max TNT Explosions: 100
[13:39:49] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:39:49] [Server thread/INFO]: View Distance: 10
[13:39:49] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:39:49] [Server thread/INFO]: Item Despawn Rate: 6000
[13:39:49] [Server thread/INFO]: Item Merge Radius: 2.5
[13:39:49] [Server thread/INFO]: Arrow Despawn Rate: 1200
[13:39:49] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:39:49] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:39:49] [Server thread/INFO]: -------- World Settings For [GabLand2_the_end] --------
[13:39:49] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Carrot Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Potato Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Vine Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Kelp Growth Modifier: 100%
[13:39:49] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:39:49] [Server thread/INFO]: Mob Spawn Range: 6
[13:39:49] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[13:39:49] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:39:49] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:39:49] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[13:39:49] [Server thread/INFO]: Max TNT Explosions: 100
[13:39:49] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:39:49] [Server thread/INFO]: View Distance: 10
[13:39:49] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:39:49] [Server thread/INFO]: Item Despawn Rate: 6000
[13:39:49] [Server thread/INFO]: Item Merge Radius: 2.5
[13:39:49] [Server thread/INFO]: Arrow Despawn Rate: 1200
[13:39:49] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:39:49] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:39:49] [Server thread/INFO]: Preparing start region for dimension 'GabLand2'/minecraft:overworld
[13:39:50] [Server thread/INFO]: Preparing spawn area: 0%
[13:39:50] [Server thread/INFO]: Preparing spawn area: 0%
[13:39:50] [Server thread/INFO]: Preparing spawn area: 0%
[13:39:50] [Server thread/INFO]: Preparing spawn area: 63%
[13:39:51] [Server thread/INFO]: Time elapsed: 1860 ms
[13:39:51] [Server thread/INFO]: Preparing start region for dimension 'GabLand2_nether'/minecraft:the_nether
[13:39:51] [Server thread/INFO]: Preparing spawn area: 0%
[13:39:51] [Server thread/INFO]: Preparing spawn area: 0%
[13:39:52] [Server-Worker-3/INFO]: Preparing spawn area: 94%
[13:39:52] [Server-Worker-3/INFO]: Preparing spawn area: 94%
[13:39:53] [Server-Worker-2/INFO]: Preparing spawn area: 95%
[13:39:53] [Server thread/INFO]: Time elapsed: 2301 ms
[13:39:53] [Server thread/INFO]: Preparing start region for dimension 'GabLand2_the_end'/minecraft:the_end
[13:39:53] [Server thread/INFO]: Preparing spawn area: 0%
[13:39:53] [Server-Worker-2/INFO]: Preparing spawn area: 83%
[13:39:54] [Server-Worker-2/INFO]: Preparing spawn area: 87%
[13:39:54] [Server thread/INFO]: Time elapsed: 1227 ms
[13:39:54] [Server thread/INFO]: [AdditionsAPI] Enabling AdditionsAPI v1.3.2
[13:39:55] [Server thread/INFO]: [VanillaAdditions] Enabling VanillaAdditions v1.3.3
[13:39:55] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:39:55] [Server thread/INFO]: Done (15.740s)! For help, type "help"
[13:39:55] [Server thread/INFO]: Starting AdditionsAPI Intialization
[13:39:55] [Server thread/INFO]: Recieved in total 206 Custom Items!
[13:39:56] [Server thread/INFO]: Finished Initialization.
[13:39:56] [Server thread/WARN]: [AdditionsAPI] Task #2 for AdditionsAPI v1.3.2 generated an exception
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at us.fihgu.toolbox.file.FileUtils.deleteFolder(FileUtils.java:60) ~[?:?]
	at us.fihgu.toolbox.resourcepack.ResourcePackManager.buildResourcePack(ResourcePackManager.java:113) ~[?:?]
	at com.chrismin13.additionsapi.AdditionsAPI.setupHTTPServer(AdditionsAPI.java:189) ~[?:?]
	at com.chrismin13.additionsapi.AdditionsAPI.load(AdditionsAPI.java:214) ~[?:?]
	at com.chrismin13.additionsapi.AdditionsAPI.lambda$onEnable$0(AdditionsAPI.java:176) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-94af569-6ddeb98]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 12 more`

**Comment by gabsoftware** [comment]
Any progress on compatibility with 1.14.4? :)

**Comment by gabsoftware** [comment]
And now with 1.15? 
Ok, i'll stop harassing you with that :)

**Comment by DrkMatr1984** [comment]
They removed commons-io from spigot in 1.14.4. This is actually a really easy fix and if you need a working jar you can find me on spigot with the same name, just pm me there and i can compile one for you.

**Comment by DrkMatr1984** [comment]
https://github.com/MinevoltRPG/AdditionsAPI/releases
Let me know if u find any bugs. I'll try to fix before putting in a PR to @chrismin13

**Comment by chrismin13** [comment]
@DrkMatr1984 I've added you as a collaborator. Since I am no longer working on the project, feel free to make changes as you see fit.

**Comment by DrkMatr1984** [comment]
[Commit cbb1c98b2ac24630cda7104ae49f0ea2e9f4fbce](https://github.com/chrismin13/AdditionsAPI/commit/cbb1c98b2ac24630cda7104ae49f0ea2e9f4fbce) fixes this.
There is a jar for 1.13-1.14 [here](https://github.com/chrismin13/AdditionsAPI/releases/download/v1.3.3-1.13-1.14/AdditionsAPI-for-1.13.jar)
1.15 [here](https://github.com/MinevoltRPG/AdditionsAPI/releases/download/1.15/AdditionsAPI-for-1.15.jar)

**Comment by gabsoftware** [comment]
Sorry just DrkMatr1984 and chrismin, just saw your messages.

When I try to start my Spigot 1.15 server with DrkMatr1984 build of Addition API for 1.15 and Vanilla Additions for 1.13 and above, I have the following error:

```
[14:14:50] [Server thread/INFO]: Starting AdditionsAPI Intialization
[14:14:50] [Server thread/ERROR]: Could not pass event AdditionsAPIInitializationEvent to VanillaAdditions v1.3.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at com.chrismin13.additionsapi.AdditionsAPI.load(AdditionsAPI.java:205) ~[?:?]
        at com.chrismin13.additionsapi.AdditionsAPI.lambda$onEnable$0(AdditionsAPI.java:176) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.IllegalStateException: Unable to find method createTag ([byte]).
        at com.comphenix.attribute.NbtFactory.getMethod(NbtFactory.java:741) ~[?:?]
        at com.comphenix.attribute.NbtFactory.<init>(NbtFactory.java:341) ~[?:?]
        at com.comphenix.attribute.NbtFactory.get(NbtFactory.java:319) ~[?:?]
        at com.comphenix.attribute.NbtFactory.createCompound(NbtFactory.java:424) ~[?:?]
        at com.comphenix.attribute.Attributes$Attribute.<init>(Attributes.java:148) ~[?:?]
        at com.comphenix.attribute.Attributes$Attribute.<init>(Attributes.java:144) ~[?:?]
        at com.comphenix.attribute.Attributes$Attribute$Builder.build(Attributes.java:275) ~[?:?]
        at com.chrismin13.additionsapi.items.CustomItem.addAttribute(CustomItem.java:490) ~[?:?]
        at com.chrismin13.additionsapi.items.CustomItem.addAttribute(CustomItem.java:460) ~[?:?]
        at com.chrismin13.additionsapi.items.CustomTool.addAttackSpeed(CustomTool.java:103) ~[?:?]
        at com.chrismin13.vanillaadditions.abilities.DoubleAxeAbilities.modifyCustomItem(DoubleAxeAbilities.java:26) ~[?:?]
        at com.chrismin13.vanillaadditions.abilities.DoubleAxeAbilities.modifyCustomItem(DoubleAxeAbilities.java:21) ~[?:?]
        at com.chrismin13.vanillaadditions.items.doubleaxes.EmeraldDoubleAxe.<init>(EmeraldDoubleAxe.java:15) ~[?:?]
        at com.chrismin13.vanillaadditions.Items.onInitialization(Items.java:169) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        ... 12 more
[14:14:50] [Server thread/INFO]: Recieved in total 0 Custom Items!

```

**Comment by DrkMatr1984** [comment]
It seems like they have removed the createTag method from NBTBase in minecraft NMS. I'm trying to find out the replacement :)
