### ISSUE TITLE
Could not pass event EnchantItemEvent to AdditionsAPI v1.2.9

### ISSUE THREAD

**Issue by andris155** [chrismin13/AdditionsAPI#5]
```
[10:42:42] [Server thread/ERROR]: Could not pass event EnchantItemEvent to AdditionsAPI v1.2.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1373]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.ContainerEnchantTable.a(ContainerEnchantTable.java:253) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2088) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PacketPlayInEnchantItem.a(SourceFile:22) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PacketPlayInEnchantItem.a(SourceFile:8) ~[patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1373]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1373]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.chrismin13.additionsapi.items.CustomItemStack.updateLore(CustomItemStack.java:366) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.additionsapi.listeners.vanilla.EnchantItem.onItemEnchant(EnchantItem.java:53) ~[AdditionsAPI-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor172.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1373]
	... 17 more
```

**Comment by chrismin13** [comment]
Also fixed in the upcoming 1.3.0 release.
