### ISSUE TITLE
Too big tree error (?)

### ISSUE THREAD

**Issue by andris155** [chrismin13/AdditionsAPI#6]
```
[06:15:49] [Craft Scheduler Thread - 253/INFO]: 
[06:18:28] [Server thread/ERROR]: Could not pass event CustomItemBlockBreakEvent to VanillaAdditions v1.2.9
java.lang.StackOverflowError: null
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:38) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBranches(TreeFeller.java:111) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
	at com.chrismin13.vanillaadditions.utils.TreeFeller.getBlocksToChop(TreeFeller.java:45) ~[VanillaAdditions-1.2.7-SNAPSHOT-shaded.jar:?]
```

**Comment by chrismin13** [comment]
WHAT WERE YOU CUTTING DOWN?! xD I don't think there's any easy way to solve this, since it would require a remake of the TreeFeller algorithm, and since it's quite the edge case I don't think it's worth it at the moment. I'll be hopefully further refining those mechanics in the future.

BTW, this is part of Vanilla Additions, not the Additions API, so please let me know in the Spigot thread of Vanilla Additions next time please!
