### ISSUE TITLE
Deprecated recipe api

### ISSUE THREAD

**Issue by SHADOWDANCH** [chrismin13/AdditionsAPI#9]
On plugin load i have this errors in console.
PaperSpigot 1.12.2
```
[13:50:03] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[13:50:03] [Server thread/WARN]: 	at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:26)
[13:50:03] [Server thread/WARN]: 	at com.chrismin13.additionsapi.recipes.CustomShapedRecipe.toBukkitRecipe(CustomShapedRecipe.java:91)
[13:50:03] [Server thread/WARN]: 	at com.chrismin13.additionsapi.recipes.CustomShapedRecipe.toBukkitRecipe(CustomShapedRecipe.java:1)
[13:50:03] [Server thread/WARN]: 	at com.chrismin13.additionsapi.recipes.CustomRecipe.registerBukkitRecipe(CustomRecipe.java:12)
[13:50:03] [Server thread/WARN]: 	at com.chrismin13.additionsapi.AdditionsAPI.onInitialization(AdditionsAPI.java:275)
[13:50:03] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source)
[13:50:03] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[13:50:03] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:50:03] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:50:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527)
[13:50:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512)
[13:50:03] [Server thread/WARN]: 	at com.chrismin13.additionsapi.AdditionsAPI.load(AdditionsAPI.java:194)
[13:50:03] [Server thread/WARN]: 	at com.chrismin13.additionsapi.AdditionsAPI.lambda$0(AdditionsAPI.java:165)
[13:50:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[13:50:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[13:50:03] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839)
[13:50:03] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[13:50:03] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[13:50:03] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[13:50:03] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chrismin13** [comment]
PaperSpigot isn't supported, only normal Spigot is supported. That being said, the plugin should still work fine. This error will be fixed in a future 1.13 release.
